---
title: "Censoring Exploration"
author: "Sara Stoudt"
date: "2/16/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning= F, message = F}
library(dplyr)
library(ggplot2)

setwd("~/Desktop/kidz-bop-data/")
#badWordSummary = read.csv("data/censoring/censoringTimes.csv", stringsAsFactors = F)
#fullData = read.csv("data/censoring/fullDataSet.csv", stringsAsFactors = F)
fullData = read.csv("data/missing/fullCensor.csv", stringsAsFactors = F)

#load(file="data/2020-02-02/ogLyricsFullPlain.RData") ## ogLyricsFull
#load(file="data/2020-02-02/kbLyrics.RData") ## kbLyrics

#kb40_gender <- read.csv("data/2020-02-02/originalArtists_gender-KB_40.csv", stringsAsFactors = F)
```

## What is being censored by category?

```{r}
fullData %>% group_by(category) %>% summarise(countCensored=sum(isCensored), count = sum(isPresent)) %>% mutate(prop = countCensored/count) %>% arrange(desc(prop))

```


## Censoring over time

```{r}
overTime = fullData %>% group_by(kb_release_year) %>% summarise(countCensored=sum(isCensored), count = sum(isPresent)) %>% mutate(prop = countCensored/count)

ggplot(overTime, aes(kb_release_year,count))+geom_point()+geom_line()+ylab("existence of words")
# picking songs that don't need as much censoring?

ggplot(overTime, aes(kb_release_year,prop))+geom_point()+geom_line()+ylab("censored / present")
# proportion of potentially problematic words being removed over time
```

Well that is striking.

## Time Trends Per Category

```{r,fig.height=12, fig.width=12}
overTime = fullData %>% group_by(kb_release_year,category) %>% summarise(countCensored=sum(isCensored), count = sum(isPresent)) %>% mutate(prop = countCensored/count)


ggplot(overTime, aes(kb_release_year,count))+geom_point()+geom_line()+facet_wrap(~category)+ylab("existence of words")

ggplot(overTime, aes(kb_release_year,prop))+geom_point()+geom_line()+facet_wrap(~category)+ylab("censored / present")



```

Slight increase in existence of alcohol & drugs and profanity over time. 

Censorship of alcohol and drugs, sexual groups increasing over time. 

